### ISSUE TITLE
There's no notification (task bar icon or pop-up) on Windows Desktop for currently _selected_ chat/channel

### ISSUE THREAD

**Issue by maxmukhin88** [mattermost/desktop#1234]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
There's no notification (task bar icon or pop-up) on Windows Desktop for currently _selected_ chat/channel

**Steps to reproduce**

Please include all of the following:
- Operating System: Windows 10
- Mattermost Desktop App version (See **Help > Version Number**): 4.4.0
- Mattermost Server version (See **Mattermost Menu > About Mattermost**, where **Mattermost Menu** can be accessed by clicking on three dots next to your profile picture): no such option, self-hosted

- set the following notification settings:
Send desktop notifications: only for mentions and direct messages

- SELECT one of the direct messages or channels
- close the application (hit Cross in top right corner)
- receive the new message in the selected direct message or channel

**Expected behavior**
- THERE IS a red dot for a new unread mention or direct message OR a blue dot for a new unread message in the channel
- a notification POPS UP for a new mention or direct message

**Observed behavior**
- THERE IS NO red dot for a new unread mention or direct message OR a blue dot for a new unread message in the channel 
- a notification DOES NOT POP UP for a new mention or direct message

Expected behavior occurs for any other direct message or a channel except for the currently selected one.
Problem seems to occur in Windows Desktop only. Problem IS NOT reproduced in Linux Desktop or Web version in Chrome.

It looks like Windows Desktop app won't detect selected chat as closed when the app is closed.

**Comment by toha134** [comment]
I have some problem. Found some issue https://github.com/mattermost/desktop/issues/1220

**Comment by amyblais** [comment]
Ticket was opened here: https://mattermost.atlassian.net/browse/MM-23215.

**Comment by erlking** [comment]
we experienced exactly the same issue today, took me a while to find out that 
- it breaks only for current selected channel
- only the desktop app is affected

works fine in browser and andoid app, hope client gets fixed soon.

**Comment by ImreSzebelledi** [comment]
Same here. Very annoying.

**Comment by maxmukhin88** [comment]
> Ticket was opened here: https://mattermost.atlassian.net/browse/MM-23215.

Would it be possible to allow watching JIRA issues for external users such as myself?

**Comment by ndi123** [comment]
It would be nice if the problem could be solved quickly

**Comment by GitRon** [comment]
Same here. Only since the update to v4.4.0 for me.

**Comment by torre76** [comment]
This bug happens also on *Mac* version.

**Comment by airmaticShared** [comment]
I can confirm that with 4.3.2 this issue is not present but 4.4 has this bug

**Comment by burnb** [comment]
Same bug on ubuntu and 4.4 version. Version 4.3.2 doesn't has this issue. And yes it's very annoying.

**Comment by ilyakonovalenko** [comment]
I believe the problem is that MatterMost marks the messages in the selected chat as read immediately so that there are no notifications in both desktop, web and mobile clients.

**Comment by ImreSzebelledi** [comment]
They claim that it is resolved by 4.4.1 but it is not.

**Comment by GitRon** [comment]
I didnt see it in the changelog so I guess the bug is still there.

**Comment by ImreSzebelledi** [comment]
You are right, I have seen that it is now resolved so I assumed it is included in the new release, but true enough it is not in the changelog.

**Comment by amyblais** [comment]
This will be fixed in upcoming v4.4.2 dot release,

**Comment by GitRon** [comment]
> 
> 
> This will be fixed in upcoming v4.4.2 dot release,

@amyblais Could you post it here when the version is released? Thx 😃

**Comment by Willyfrog** [comment]
there is currently an RC for the release https://github.com/mattermost/desktop/releases/tag/v4.4.2-rc1

**Comment by amyblais** [comment]
This is now fixed in v4.4.2 https://github.com/mattermost/desktop/releases/tag/v4.4.2.

**Comment by ImreSzebelledi** [comment]
It really is. Thank you very much! (:

**Comment by maxmukhin88** [comment]
Thanks so much for fixing this!
