### ISSUE TITLE
Don't show the collapse/expand arrow for HTTP image links when non-secure content is disabled

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#433]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
Don't show the collapse/expand arrow for HTTP image links when non-secure content is disabled

**Steps to reproduce**

Windwos 10; Mattermost Desktop v3.5; Mattermost Server v3.6.2

1) Go to File > Settings and disable the setting `Allow mixed content`
2) Hit "Save"
3) Go to Account Settings > Display and set **Link Previews** to Off
4) Post this link to a Mattermost channel: http://www.mattermost.org/wp-content/uploads/2016/03/logoHorizontal.png

**Expected behavior**

Image link doesn't render. No collapse/expand arrow shown for the link.

**Observed behavior**

Image link doesn't render. However, collapse/expand arrows are shown to the user, indicating that the image could be expanded. 

![image](https://cloud.githubusercontent.com/assets/13119842/22866707/d6c4ef8e-f148-11e6-9e22-01554fd4147d.png)

Clicking the arrow hides it, and no image is rendered.
![image](https://cloud.githubusercontent.com/assets/13119842/22866710/ddbff77a-f148-11e6-8515-298289bef211.png)

**Possible fixes**

?

**Comment by yuya-oc** [comment]
It doesn't reproduce in pre-release.mattermost.com (possibly it's already fixed in webapp).

**Comment by jasonblais** [comment]
Hm, it does still reproduce for me on pre-release.mattermost.com using this link: http://www.mattermost.org/wp-content/uploads/2016/03/logoHorizontal.png

**Comment by jasonblais** [comment]
Although on pre-release, step 3 has changed to **Account Settings > Display > Default appearance of image link previews** = Collapsed

**Comment by yuya-oc** [comment]
Thanks, reproduced. However it seems that this is issue for webapp. It also reproduce on Chrome when using a broken link, e.g. https://example.com/not-exist.png (http 404).

**Comment by jasonblais** [comment]
Ah, got it. I've created an issue on the server side: https://mattermost.atlassian.net/browse/PLT-5478
