### ISSUE TITLE
Mattermost Desktop App v3.7.0 - RC1 is out!

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#516]
Hello - and huge thanks to everyone for contributing to the Mattermost Desktop project!

Given our recent progress, we feel we’re ready to release v3.7 soon. Here are the proposed dates (all tentative and subject to change):

- Friday 4/28: Code complete with `release-3.7` locked in the desktop repo
- Monday 5/1: Testing begins on the release candidate
- Friday 5/5: Date to cut the final release
- Tuesday 5/9: Official release with marketing

Below is a list of remaining issues for the release:

 - @yuya-oc [Add spellchecker](https://github.com/mattermost/desktop/pull/277)
 - @yuya-oc [Clicking a public file link opens an extra Mattermost window, in addition to downloading the file](https://github.com/mattermost/desktop/pull/390)
 - @jnugh [Add display-metrics-changed handler to place window on screen](https://github.com/mattermost/desktop/pull/420)
 - @jasonblais [Review README.md and CONTRIBUTING.md files](https://github.com/mattermost/desktop/pull/472)

Yuya and Jason

**Comment by jasonblais** [comment]
RC1 for v3.7 has been cut! Download links available to test below. Please link to issues you believe may warrant a patch.

Mattermost Desktop App 3.7 is scheduled for a release on May 9th. 

[See changelog for details on what's new](https://github.com/mattermost/desktop/blob/release-3.7/CHANGELOG.md#release-v370).

**Windows Installers**

https://releases.mattermost.com/desktop/3.7.0-rc1/mattermost-setup-3.7.0-rc1-win64.exe
https://releases.mattermost.com/desktop/3.7.0-rc1/mattermost-setup-3.7.0-rc1-win32.exe

**Windows - Zip**

https://releases.mattermost.com/desktop/3.7.0-rc1/mattermost-desktop-3.7.0-rc1-win64.zip
https://releases.mattermost.com/desktop/3.7.0-rc1/mattermost-desktop-3.7.0-rc1-win32.zip

**Mac**

https://releases.mattermost.com/desktop/3.7.0-rc1/mattermost-desktop-3.7.0-rc1-osx.tar.gz

**Linux (Beta)**

https://releases.mattermost.com/desktop/3.7.0-rc1/mattermost-desktop-3.7.0-rc1-linux-x64.tar.gz
https://releases.mattermost.com/desktop/3.7.0-rc1/mattermost-desktop-3.7.0-rc1-linux-ia32.tar.gz

**Linux - Debian (Unofficial)**

https://releases.mattermost.com/desktop/3.7.0-rc1/mattermost-desktop-3.7.0-rc1-linux-amd64.deb
https://releases.mattermost.com/desktop/3.7.0-rc1/mattermost-desktop-3.7.0-rc1-linux-i386.deb

**Comment by Hanzei** [comment]
The link to the debian packges returns a 403 error

**Comment by jasonblais** [comment]
@yuya-oc can you help take a look?

It looks like all but Linux builds give a 403 error, only `https://releases.mattermost.com/desktop/3.7.0-rc1/mattermost-desktop-3.7.0-rc1-linux-ia32.tar.gz` works.

**Comment by jasonblais** [comment]
And thanks @Hanzei for your interest trying out the release candidate

**Comment by asalmela** [comment]
Links to Linux binaries give 403 for me.

**Comment by yuya-oc** [comment]
Thanks to let me know. The link is unexpectedly different from previous version. For now, I have fixed the link and confirmed that all links are actually available.

**Comment by Hanzei** [comment]
https://releases.mattermost.com/desktop/3.7.0-rc1/mattermost-desktop-3.7.0-rc1-linux-x64.tar.gz and the two debian links still dont work

**Comment by yuya-oc** [comment]
Added a new issue #523

**Comment by jasonblais** [comment]
#### Approved fixes for RC2
 - [Enable spellchecker by default](https://github.com/mattermost/desktop/pull/529)
 - [Reset misspelling state after changing spelling language](https://github.com/mattermost/desktop/pull/526)

**Comment by jasonblais** [comment]
**Windows Installers**

https://releases.mattermost.com/desktop/3.7.0-rc2/mattermost-setup-3.7.0-rc2-win64.exe
https://releases.mattermost.com/desktop/3.7.0-rc2/mattermost-setup-3.7.0-rc2-win32.exe

**Windows - Zip**

https://releases.mattermost.com/desktop/3.7.0-rc2/mattermost-desktop-3.7.0-rc2-win64.zip
https://releases.mattermost.com/desktop/3.7.0-rc2/mattermost-desktop-3.7.0-rc2-win32.zip

**Mac**

https://releases.mattermost.com/desktop/3.7.0-rc2/mattermost-desktop-3.7.0-rc2-osx.tar.gz

**Linux (Beta)**

https://releases.mattermost.com/desktop/3.7.0-rc2/mattermost-desktop-3.7.0-rc2-3.7.0.tar.gz
https://releases.mattermost.com/desktop/3.7.0-rc2/mattermost-desktop-3.7.0-rc2-linux-ia32.tar.gz

**Linux - Debian (Unofficial)**

https://releases.mattermost.com/desktop/3.7.0-rc2/mattermost-desktop-3.7.0-rc2-linux-amd64.deb
https://releases.mattermost.com/desktop/3.7.0-rc2/mattermost-desktop-3.7.0-rc2-linux-i386.deb

**Comment by jasonblais** [comment]
Mattermost Desktop App v3.7.0 is now cut: https://github.com/mattermost/desktop/releases/tag/v3.7.0

We'll do code-signing later today and publish the release at https://github.com/mattermost/desktop/releases

Thanks to all who helped test the app!
