### ISSUE TITLE
Suggestion for displaying link url bar.

### ISSUE THREAD

**Issue by Domvel** [mattermost/desktop#689]
Hold on, do not close it as duplicate. I know there are some tickets of this topic. But this is a kind different.
It's a appearance solution for the hyperlink url bar at the bottom. 

That's the current appearance and a really annoying problem. Because you cannot see if someone is wrting and it's just overlay the ui.
![mat-now-problem](https://user-images.githubusercontent.com/35452565/35268918-d34d7032-002a-11e8-8767-5bd5355d09c2.jpg)

That's my suggestion. Just pad the bottom for exact 25px. That's the height of the url bar at the bottom. 
![mat-suggestion](https://user-images.githubusercontent.com/35452565/35268920-d5638672-002a-11e8-81ee-0b1c7aca90c5.jpg)

I think this is a very quick solution and will fix the issue as desired.
I know, in another issue the sidebar links (a-tags) are replaced to buttons. But this isn't the topic of this ticket. It's descripes all links. Also user posted links.
It's really annoying, because the mouse will always hover a link accidentally.

Desktop Version: 3.7.1 (latest at this moment)
(Btw. when is a update planned? With the a-tag in button fix?)

**Comment by jasonblais** [comment]
Thoughts @yuya-oc? Seems like a simple fix but I'm not sure if this is feasible in the Electron framework.

// cc @amyblais

**Comment by Domvel** [comment]
Just CSS padding-bottom: 25px for the top wrapper?!

**Comment by yuya-oc** [comment]
I never thought until now. Probably we need to consider about appearance though, the idea looks not bad.

**Comment by jasonblais** [comment]
I've touched base with our designers to hear their thoughts.

**Comment by Domvel** [comment]
Ok, great. This is a preview of the whole window. Maybe not the prettiest solution. But effective.
Btw. this "padding" should only affect for the desktop app (electron). And maybe, this can be a option in an appearance section in the settings of the app. If people are not completely convinced. Whatever ...
Just a suggestion.

![Url-Bar-Demo](https://user-images.githubusercontent.com/35452565/35403448-060b98d8-0200-11e8-9efd-a30e0f55dd88.jpg)

**Comment by jasonblais** [comment]
@Domvel This issue should be resolved for Mattermost Servers v4.4 and later, where none of the internal links show the URL on hover.

**Comment by Domvel** [comment]
@jasonblais This is not exactly the reason of this issue. This is a suggestion how to display the url-bar. Regardless of the show-internal-link issue. And btw. the internal-link-issue is not fixed 100% server side. For example: Hover the timestamp of a message. But anyway. As long as the url bar is displayed, this ticket suggest the way how to display. (also for user posted links). ... I'll accept a rejection. But I want to make sure that you understood my request. :)

**Comment by jasonblais** [comment]
Thanks @Domvel! And yeah, understood the request - the concern at the moment for me is the appearance/style.

And thanks for the heads up on having a URL when hovering the timestamp! This is a bug, and have filed a ticket here: https://mattermost.atlassian.net/browse/MM-9922
